### ISSUE TITLE
Can this be compiled or used without VS2008? Or can a compiled binary be provided in git?

### ISSUE THREAD

**Issue by neildufva** [kennethnoyens/httpToCrestronSignal#1]
Just wondering if its possible to have a compiled binary available so you dont have to have visual studio 2008 pro? We cant get VS2008 to install on any of our machines most likely because the frameworks it tries to reach out for online are no longer provided that are needed for installation... Is there anyway to implement this module without having VS2008?

**Comment by kennethnoyens** [comment]
Unfortunately this is not possible as I'm not the owner of the (binary) code that will be included in the .clz  created by the Crestron SIMPL# plugin for VS2008.

You can compile this with a pro version of VS2008 that has the official Crestron SIMPL# plugin installed.
